/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anouncement: typeof import('./components/Anouncement.vue')['default']
    ComingSoon: typeof import('./components/zzz/ComingSoon.vue')['default']
    CommingSoon: typeof import('./components/zzz/ComingSoon.vue')['default']
    FeatureProduct: typeof import('./components/zzz/FeatureProduct.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuList: typeof import('./components/MenuList.vue')['default']
    NewArrival: typeof import('./components/zzz/NewArrival.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/Slider.vue')['default']
    TopHeader: typeof import('./components/zzz/TopHeader.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
  }
}
